import { jsPDF } from "jspdf";
import { BASE_URL } from "@/lib/config";
import { memberFetchWithAuthRetry } from "@/lib/memberAuthedFetch";
import {
  getMatchChartJson,
  type HoroscopeMeData,
  type HoroscopePrimaryPanel,
  type MatchBlock,
  type MatchChartPersonJson,
  type PoruthamDetailedItem,
} from "@/lib/astrologyApi";
import { poruthamRowsFromMatch } from "@/lib/astrologyPoruthamDisplay";
import { panelsBrideGroom } from "@/lib/astrologyBrideGroomPanels";
import { formatDateDdMmYyyy, formatTimeOfBirthDisplay } from "@/lib/utils";
import {
  normalizeChartPlanetsMap,
  SOUTH_INDIAN_CELL_RC,
  SOUTH_INDIAN_GRID_SIGNS,
} from "@/components/astrology/southIndianChartLayout";

const MAROON: [number, number, number] = [139, 35, 87];
const GOLD: [number, number, number] = [184, 134, 11];
const TAN_BORDER: [number, number, number] = [166, 124, 82];
const ROW_ALT: [number, number, number] = [232, 242, 252];
const GREEN: [number, number, number] = [46, 125, 50];
const BLUE: [number, number, number] = [25, 118, 210];
const RED: [number, number, number] = [198, 40, 40];
const FOOTER_TEXT = "Generated by Toqse Matrimony";

function stripKeralaDashakootSuffix(text: string): string {
  return text.replace(/\s*[—-]\s*Kerala\s+Dashakoot\s+System\s*$/i, "").trim();
}

function resolveMediaUrl(pathOrUrl: string): string {
  const t = pathOrUrl.trim();
  if (!t) return "";
  if (/^https?:\/\//i.test(t)) return t;
  const base = BASE_URL.replace(/\/api\/?$/i, "").replace(/\/$/, "");
  return `${base}${t.startsWith("/") ? "" : "/"}${t}`;
}

function roleLabelForPanel(
  panel: HoroscopePrimaryPanel,
  match: MatchBlock,
  fallback: "Bride" | "Groom",
): "Bride" | "Groom" {
  const matri = panel.matri_id?.trim();
  if (matri && match.bride_matri_id?.trim() === matri) return "Bride";
  if (matri && match.groom_matri_id?.trim() === matri) return "Groom";
  const role = (panel.role ?? "").toLowerCase();
  if (role.includes("bride")) return "Bride";
  if (role.includes("groom")) return "Groom";
  return fallback;
}

function birthForPanel(
  panel: HoroscopePrimaryPanel,
  root: HoroscopeMeData,
  userMatriId: string,
): { dob: string; tob: string; pob: string } {
  const panelDob = formatDateDdMmYyyy(panel.date_of_birth ?? "");
  const panelTob = formatTimeOfBirthDisplay(panel.time_of_birth);
  const panelPob = panel.place_of_birth?.trim() || "—";
  const hasPanelBirth =
    (panel.date_of_birth != null && String(panel.date_of_birth).trim() !== "") ||
    (panel.time_of_birth != null && String(panel.time_of_birth).trim() !== "") ||
    (panel.place_of_birth != null && String(panel.place_of_birth).trim() !== "");
  if (hasPanelBirth) {
    return { dob: panelDob, tob: panelTob, pob: panelPob };
  }

  const uid = userMatriId.trim();
  if (panel.matri_id && uid && panel.matri_id === uid) {
    return {
      dob: formatDateDdMmYyyy(root.date_of_birth ?? ""),
      tob: formatTimeOfBirthDisplay(root.time_of_birth),
      pob: root.place_of_birth?.trim() || "—",
    };
  }
  return { dob: "—", tob: "—", pob: "—" };
}

function panelNakshatraLine(panel: HoroscopePrimaryPanel): string {
  const cp = panel.center_panel;
  const n =
    cp?.nakshatra ??
    panel.nakshatra_label ??
    panel.nakshatra ??
    panel.chart_meta?.nakshatra_label ??
    "";
  const en = cp?.nakshatra_english?.trim();
  const parts = [n, en].filter(Boolean);
  return parts.join(" · ") || "—";
}

function panelPadaRasi(panel: HoroscopePrimaryPanel): string {
  const cp = panel.center_panel;
  const pada = cp?.padam ?? panel.nakshatra_pada;
  const rasi =
    panel.chart_meta?.rasi_label?.trim() ||
    panel.rasi?.trim() ||
    "";
  const bits = [
    pada != null ? `Pada ${pada}` : "",
    rasi ? `${rasi}` : "",
  ].filter(Boolean);
  return bits.join(" | ") || "—";
}

async function fetchImageDataUrl(url: string): Promise<string | null> {
  const abs = resolveMediaUrl(url);
  if (!abs) return null;
  try {
    const res = await memberFetchWithAuthRetry(abs, { method: "GET" });
    if (!res.ok) return null;
    const blob = await res.blob();
    if (!blob.size) return null;
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () =>
        resolve(typeof reader.result === "string" ? reader.result : null);
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function scoreResultLabel(item: PoruthamDetailedItem): { text: string; rgb: [number, number, number] } {
  const pts = item.points;
  if (typeof pts === "number") {
    if (pts >= 1) return { text: "✓ Uttamam", rgb: GREEN };
    if (pts >= 0.5) return { text: "~ Madhyam", rgb: BLUE };
    return { text: "✗ Thypthikaramalla", rgb: RED };
  }
  return item.matched
    ? { text: "✓ Uttamam", rgb: GREEN }
    : { text: "✗ Thypthikaramalla", rgb: RED };
}

function drawFooter(doc: jsPDF, page: number, totalPages: number) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const barH = 8;
  doc.setFillColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.rect(0, h - barH, w, barH, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255);
  doc.text(FOOTER_TEXT, 10, h - 3);
  doc.text(`Page ${page} of ${totalPages}`, w - 10, h - 3, { align: "right" });
}

function drawMaroonBanner(doc: jsPDF, y: number, title: string, subtitle: string): number {
  const w = doc.internal.pageSize.getWidth();
  const m = 12;
  const bannerH = 22;
  doc.setFillColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.rect(m, y, w - 2 * m, bannerH, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(title, w / 2, y + 9, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(subtitle, w / 2, y + 16, { align: "center" });
  return y + bannerH + 4;
}

function southIndianChartDataUrl(person: MatchChartPersonJson, sizePx = 920): string | null {
  if (typeof document === "undefined") return null;
  const canvas = document.createElement("canvas");
  canvas.width = sizePx;
  canvas.height = sizePx;
  const ctx = canvas.getContext("2d");
  if (!ctx) return null;

  const cardPad = Math.round(sizePx * 0.04);
  const gridSize = sizePx - cardPad * 2;
  const cell = gridSize / 4;
  const planets = normalizeChartPlanetsMap(person.planets);
  ctx.fillStyle = "#fff7fb";
  ctx.fillRect(0, 0, sizePx, sizePx);
  ctx.strokeStyle = "#d9bfd0";
  ctx.lineWidth = 2.5;
  ctx.strokeRect(cardPad / 2, cardPad / 2, sizePx - cardPad, sizePx - cardPad);
  for (let i = 0; i < SOUTH_INDIAN_GRID_SIGNS.length; i++) {
    const sign = SOUTH_INDIAN_GRID_SIGNS[i];
    const { row, col } = SOUTH_INDIAN_CELL_RC[i];
    const x = cardPad + (col - 1) * cell;
    const y = cardPad + (row - 1) * cell;
    ctx.fillStyle = "#f7dce8";
    ctx.fillRect(x, y, cell, cell);
    ctx.strokeStyle = "#d9bfd0";
    ctx.lineWidth = 1.2;
    ctx.strokeRect(x, y, cell, cell);

    ctx.fillStyle = "#8b2357";
    ctx.font = "bold 14px Arial";
    ctx.fillText(sign.slice(0, 3).toUpperCase(), x + 8, y + 22);

    ctx.fillStyle = "#333";
    ctx.font = "500 15px 'Noto Sans Malayalam', Arial, sans-serif";
    const bodies = planets[sign] ?? [];
    let ty = y + 42;
    for (const b of bodies.slice(0, 5)) {
      ctx.fillText(String(b), x + 8, ty);
      ty += 18;
    }
  }

  const cx = cardPad + cell;
  const cy = cardPad + cell;
  const cSize = cell * 2;
  ctx.fillStyle = "#fdf8fc";
  ctx.fillRect(cx, cy, cSize, cSize);
  ctx.strokeStyle = "#d9bfd0";
  ctx.strokeRect(cx, cy, cSize, cSize);

  ctx.fillStyle = "#8b2357";
  ctx.textAlign = "center";
  ctx.font = "bold 22px 'Noto Sans Malayalam', Arial, sans-serif";
  const nm = (person.name ?? "").trim() || "—";
  ctx.fillText(nm, cx + cSize / 2, cy + 42);

  ctx.fillStyle = "#3a3a3a";
  ctx.font = "500 16px 'Noto Sans Malayalam', Arial, sans-serif";
  if (person.nakshatra) {
    const nk = `${person.nakshatra}${person.nakshatra_pada != null ? ` · P${person.nakshatra_pada}` : ""}`;
    ctx.fillText(nk, cx + cSize / 2, cy + 78);
  }
  if (person.dasa_lord) {
    ctx.fillText(`Lord: ${person.dasa_lord}`, cx + cSize / 2, cy + 102);
  }
  if (person.dasa_balance) {
    ctx.fillText(`Dasa: ${person.dasa_balance}`, cx + cSize / 2, cy + 122);
  }
  const lr = [
    person.lagna ? `Lagna ${person.lagna}` : "",
    person.rasi ? `Rasi ${person.rasi}` : "",
  ]
    .filter(Boolean)
    .join(" · ");
  if (lr) ctx.fillText(lr, cx + cSize / 2, cy + 144);
  ctx.textAlign = "start";
  return canvas.toDataURL("image/png");
}

function poruthamDescriptionForKeys(
  rows: PoruthamDetailedItem[],
  keys: string[],
): string {
  for (const want of keys) {
    const row = rows.find(
      (r) =>
        normalizeKey(r.key).includes(want) ||
        normalizeKey(r.label).includes(want),
    );
    const d = row?.description?.trim();
    if (d) return d;
  }
  return "—";
}

function pairValuesFromDescription(desc: string): { bride: string; groom: string } | null {
  const t = desc.trim();
  if (!t) return null;

  // Preferred pattern: explanatory text with "(Bride / Groom)".
  const paren = /\(([^()]*\/[^()]*)\)/.exec(t);
  const pairText = paren?.[1] ?? t;
  if (!pairText.includes("/")) return null;

  const [leftRaw, rightRaw] = pairText.split("/").map((s) => s.trim());
  const left = leftRaw.replace(/^[^A-Za-z]+|[^A-Za-z)\]]+$/g, "").trim();
  const right = rightRaw.replace(/^[^A-Za-z]+|[^A-Za-z)\]]+$/g, "").trim();

  // Guard against sentence-like fragments being treated as values.
  if (!left || !right) return null;
  if (left.length > 28 || right.length > 28) return null;
  if (left.split(/\s+/).length > 3 || right.split(/\s+/).length > 3) return null;
  return { bride: left, groom: right };
}

function normalizeKey(s: string | undefined): string {
  return (s ?? "").toLowerCase().replace(/[\s_-]+/g, "");
}

function ensureSpace(doc: jsPDF, y: number, need: number, margin: number): number {
  const h = doc.internal.pageSize.getHeight();
  if (y + need > h - margin - 10) {
    doc.addPage();
    return margin;
  }
  return y;
}

export async function downloadMatchCompatibilityReportPdf(opts: {
  data: HoroscopeMeData;
  match: MatchBlock;
  userMatriId: string;
}): Promise<void> {
  const { data, match, userMatriId } = opts;
  const primary = data.primary;
  const partner = data.partner;
  if (!primary || !partner) throw new Error("Missing primary or partner panel.");
  const { bride, groom } =
    match.bride_profile_id != null && match.groom_profile_id != null
      ? panelsBrideGroom(
          primary,
          partner,
          match.bride_profile_id,
          match.groom_profile_id,
        )
      : { bride: primary, groom: partner };
  const brideBirth = birthForPanel(bride, data, userMatriId);
  const groomBirth = birthForPanel(groom, data, userMatriId);
  const leftRole = roleLabelForPanel(bride, match, "Bride");
  const rightRole = roleLabelForPanel(groom, match, "Groom");

  let chartPersons: { bride: MatchChartPersonJson; groom: MatchChartPersonJson } | null =
    null;
  if (match.bride_profile_id != null && match.groom_profile_id != null) {
    try {
      const json = await getMatchChartJson(
        match.bride_profile_id,
        match.groom_profile_id,
        "rasi",
      );
      chartPersons = { bride: json.bride, groom: json.groom };
    } catch {
      chartPersons = null;
    }
  }

  const brideChartUrl = bride.chart_url?.trim() ?? "";
  const groomChartUrl = groom.chart_url?.trim() ?? "";
  let brideImg: string | null = null;
  let groomImg: string | null = null;
  if (!chartPersons) {
    [brideImg, groomImg] = await Promise.all([
      brideChartUrl ? fetchImageDataUrl(brideChartUrl) : Promise.resolve(null),
      groomChartUrl ? fetchImageDataUrl(groomChartUrl) : Promise.resolve(null),
    ]);
  }

  const poruthamRowsBase = poruthamRowsFromMatch(match).map((item) => ({
    ...item,
    points: match.koota_points?.[item.key] ?? item.points,
  }));
  const ganaLine = poruthamDescriptionForKeys(poruthamRowsBase, ["ganam", "gana"]);
  const yoniLine = poruthamDescriptionForKeys(poruthamRowsBase, ["yoni"]);
  const rajjuLine = poruthamDescriptionForKeys(poruthamRowsBase, [
    "rajju",
    "rejju",
    "reju",
  ]);
  const ganaPair = pairValuesFromDescription(ganaLine);
  const yoniPair = pairValuesFromDescription(yoniLine);
  const rajjuPair = pairValuesFromDescription(rajjuLine);

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const m = 12;
  let y = m;

  const title = stripKeralaDashakootSuffix(
    data.title ?? "Marriage Compatibility Report",
  );
  const subtitle = stripKeralaDashakootSuffix(
    data.subtitle ?? "Jathaka Porutham",
  );

  y = drawMaroonBanner(doc, y, title, subtitle);

  const boxW = (pageW - 2 * m - 14) / 2;
  const boxH = 18;
  doc.setDrawColor(TAN_BORDER[0], TAN_BORDER[1], TAN_BORDER[2]);
  doc.setFillColor(248, 248, 248);
  doc.rect(m, y, boxW, boxH, "FD");
  doc.rect(m + boxW + 14, y, boxW, boxH, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text((bride.name ?? "Profile A").trim(), m + boxW / 2, y + 8, { align: "center" });
  doc.text((groom.name ?? "Profile B").trim(), m + boxW + 14 + boxW / 2, y + 8, {
    align: "center",
  });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(leftRole, m + boxW / 2, y + 14, { align: "center" });
  doc.text(rightRole, m + boxW + 14 + boxW / 2, y + 14, {
    align: "center",
  });
  doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("♥", m + boxW + 7, y + 10, { align: "center" });
  y += boxH + 3;

  doc.setDrawColor(TAN_BORDER[0], TAN_BORDER[1], TAN_BORDER[2]);
  doc.setFillColor(252, 250, 248);
  doc.rect(m, y, pageW - 2 * m, 16, "FD");
  const score = match.summary?.score ?? match.score ?? 0;
  const maxScore = match.summary?.max_score ?? match.max_score ?? 10;
  const pct =
    match.summary?.percentage ??
    (maxScore > 0 ? Math.round((score / maxScore) * 100) : null);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text(`${score}/${maxScore}`, m + 4, y + 11);
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  if (pct != null) {
    doc.text(`(${pct}%)`, m + 38, y + 7);
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const grade =
    match.summary?.result ??
    match.summary?.grade ??
    match.result ??
    "—";
  doc.text("Compatibility grade: ", m + 38, y + 12);
  const tw = doc.getTextWidth("Compatibility grade: ");
  doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.setFont("helvetica", "bold");
  doc.text(String(grade), m + 38 + tw, y + 12);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text("Personal Details", m, y);
  y += 2;
  doc.setDrawColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.line(m, y, pageW - m, y);
  y += 5;

  const rows: { label: string; b: string; g: string }[] = [
    { label: "Date of Birth", b: brideBirth.dob, g: groomBirth.dob },
    { label: "Time of Birth", b: brideBirth.tob, g: groomBirth.tob },
    { label: "Place of Birth", b: brideBirth.pob, g: groomBirth.pob },
    { label: "Janma Nakshatra", b: panelNakshatraLine(bride), g: panelNakshatraLine(groom) },
    {
      label: "Nakshatra Pada",
      b:
        bride.center_panel?.padam != null
          ? String(bride.center_panel.padam)
          : bride.nakshatra_pada != null
            ? String(bride.nakshatra_pada)
            : "—",
      g:
        groom.center_panel?.padam != null
          ? String(groom.center_panel.padam)
          : groom.nakshatra_pada != null
            ? String(groom.nakshatra_pada)
            : "—",
    },
    {
      label: "Janma Rasi",
      b: bride.chart_meta?.rasi_label ?? bride.rasi ?? "—",
      g: groom.chart_meta?.rasi_label ?? groom.rasi ?? "—",
    },
    {
      label: "Lagna",
      b: bride.chart_meta?.lagna_label ?? bride.lagna ?? "—",
      g: groom.chart_meta?.lagna_label ?? groom.lagna ?? "—",
    },
    {
      label: "Gana",
      b: ganaPair?.bride ?? "—",
      g: ganaPair?.groom ?? "—",
    },
  ];

  const col1 = m;
  const col2 = m + 42;
  const col3 = m + 105;
  const col4 = m + 138;
  rows.forEach((r, i) => {
    const bLines = doc.splitTextToSize(r.b, 58);
    const gLines = doc.splitTextToSize(r.g, 52);
    const lineCount = Math.max(bLines.length, gLines.length, 1);
    const rowH = Math.max(7, 4 + lineCount * 3.2);
    const textY = y + (rowH - 3.2 * lineCount) / 2;

    if (i % 2 === 0) {
      doc.setFillColor(ROW_ALT[0], ROW_ALT[1], ROW_ALT[2]);
      doc.rect(col1, y - 4, pageW - 2 * m, rowH, "F");
    } else {
      doc.setFillColor(255, 255, 255);
      doc.rect(col1, y - 4, pageW - 2 * m, rowH, "F");
    }
    doc.setDrawColor(TAN_BORDER[0], TAN_BORDER[1], TAN_BORDER[2]);
    doc.rect(col1, y - 4, pageW - 2 * m, rowH, "S");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
    doc.text(r.label, col1 + 1, textY);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(bLines, col2, textY);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
    doc.text(r.label, col3, textY);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(gLines, col4, textY);
    y += rowH;
  });
  y += 6;

  y = ensureSpace(doc, y, 95, m);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text("Janma Charts (Grahanila)", m, y);
  y += 2;
  doc.setDrawColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.line(m, y, pageW - m, y);
  y += 6;

  const chartBlockW = pageW - 2 * m;
  const chartSize = Math.min(72, (chartBlockW - 18) / 2);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text(
    `${(bride.name ?? "").trim() || "Profile A"} — ${leftRole}`,
    m + chartSize / 2,
    y,
    {
      align: "center",
    },
  );
  doc.text(
    `${(groom.name ?? "").trim() || "Profile B"} — ${rightRole}`,
    pageW - m - chartSize / 2,
    y,
    { align: "center" },
  );
  y += 5;

  const leftCx = m;
  const rightCx = pageW - m - chartSize;
  const chartY = y;

  if (chartPersons) {
    const leftChartImg = southIndianChartDataUrl(chartPersons.bride);
    const rightChartImg = southIndianChartDataUrl(chartPersons.groom);
    if (leftChartImg) doc.addImage(leftChartImg, "PNG", leftCx, chartY, chartSize, chartSize);
    doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("VS", pageW / 2, chartY + chartSize / 2, { align: "center" });
    if (rightChartImg)
      doc.addImage(rightChartImg, "PNG", rightCx, chartY, chartSize, chartSize);
  } else {
    const tryImg = (dataUrl: string | null, x: number) => {
      if (!dataUrl) return;
      const fmt = dataUrl.includes("image/png") ? "PNG" : "JPEG";
      try {
        doc.addImage(dataUrl, fmt, x, chartY, chartSize, chartSize);
      } catch {
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 120);
        doc.text("Chart unavailable", x + chartSize / 2, chartY + chartSize / 2, {
          align: "center",
        });
      }
    };
    tryImg(brideImg, leftCx);
    doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("VS", pageW / 2, chartY + chartSize / 2, { align: "center" });
    tryImg(groomImg, rightCx);
  }

  y = chartY + chartSize + 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text(panelNakshatraLine(bride), leftCx + chartSize / 2, y, { align: "center" });
  doc.text(panelNakshatraLine(groom), rightCx + chartSize / 2, y, { align: "center" });
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(30, 80, 160);
  doc.text(panelPadaRasi(bride), leftCx + chartSize / 2, y, { align: "center" });
  doc.text(panelPadaRasi(groom), rightCx + chartSize / 2, y, { align: "center" });
  y += 10;

  drawFooter(doc, 1, 3);

  doc.addPage();
  y = m;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text("Porutham Score", m, y);
  y += 2;
  doc.line(m, y, pageW - m, y);
  y += 5;

  const poruthamRows = poruthamRowsBase;

  const tableW = pageW - 2 * m;
  const cw0 = 8;
  const cw1 = 42;
  const cw2 = 28;
  const cw3 = 28;
  const cw4 = 12;
  const cw5 = 14;
  const cw6 = tableW - cw0 - cw1 - cw2 - cw3 - cw4 - cw5;
  const headerH = 8;
  doc.setFillColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.rect(m, y, tableW, headerH, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  let x0 = m;
  const heads = ["#", "Porutham", "Bride", "Groom", "Max", "Score", "Result"];
  const cws = [cw0, cw1, cw2, cw3, cw4, cw5, cw6];
  heads.forEach((h, i) => {
    doc.text(h, x0 + 0.5, y + 5.2);
    x0 += cws[i];
  });
  y += headerH;

  poruthamRows.forEach((item, idx) => {
    const rh = 12;
    y = ensureSpace(doc, y, rh + 2, m);
    doc.setFillColor(idx % 2 === 0 ? 255 : 252, idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 240);
    doc.rect(m, y, tableW, rh, "F");
    doc.setDrawColor(TAN_BORDER[0], TAN_BORDER[1], TAN_BORDER[2]);
    doc.rect(m, y, tableW, rh, "S");
    x0 = m;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(40, 40, 40);
    doc.text(String(idx + 1), x0 + 1, y + 5);
    x0 += cw0;
    doc.setFont("helvetica", "bold");
    doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
    const label = (item.label ?? item.key).trim();
    doc.text(label, x0 + 0.5, y + 4, { maxWidth: cw1 - 1 });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6);
    doc.setTextColor(120, 120, 120);
    if (item.description) {
      doc.text(item.description, x0 + 0.5, y + 8.5, { maxWidth: cw1 - 1 });
    }
    x0 += cw1;
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(7);
    const desc = (item.description ?? "").trim();
    const brideCell =
      desc.includes(" / ") ? desc.split(" / ")[0]?.trim() || "—" : desc || "—";
    const groomCell =
      desc.includes(" / ") ? desc.split(" / ")[1]?.trim() || "—" : desc || "—";
    doc.text(brideCell, x0 + 0.5, y + 6, { maxWidth: cw2 - 1 });
    x0 += cw2;
    doc.text(groomCell, x0 + 0.5, y + 6, { maxWidth: cw3 - 1 });
    x0 += cw3;
    doc.text("1", x0 + 1, y + 6);
    x0 += cw4;
    const pts = item.points ?? (item.matched ? 1 : 0);
    const sc = typeof pts === "number" ? pts.toFixed(1) : String(pts);
    if (pts === 1 || (typeof pts === "number" && pts >= 1))
      doc.setTextColor(GREEN[0], GREEN[1], GREEN[2]);
    else if (typeof pts === "number" && pts >= 0.5)
      doc.setTextColor(BLUE[0], BLUE[1], BLUE[2]);
    else doc.setTextColor(RED[0], RED[1], RED[2]);
    doc.setFont("helvetica", "bold");
    doc.text(sc, x0 + 0.5, y + 6);
    x0 += cw5;
    const res = scoreResultLabel(item);
    doc.setTextColor(res.rgb[0], res.rgb[1], res.rgb[2]);
    doc.setFontSize(6.5);
    doc.text(res.text, x0 + 0.5, y + 6, { maxWidth: cw6 - 1 });
    y += rh;
  });

  y = ensureSpace(doc, y, 14, m);
  doc.setFillColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.rect(m, y, tableW, 9, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.text("TOTAL SCORE", m + cw0 + cw1 + 0.5, y + 6.2);
  doc.text(String(maxScore ?? 10), m + cw0 + cw1 + cw2 + cw3 + 1, y + 6.2);
  const tot = String(score ?? "—");
  doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.text(tot, m + cw0 + cw1 + cw2 + cw3 + cw4 + 0.5, y + 6.2);
  const pct2 = match.summary?.percentage;
  const gradeLine =
    pct2 != null
      ? `${pct2}% — ${match.summary?.result ?? match.result ?? ""}`
      : (match.summary?.result ?? match.result ?? "");
  doc.text(gradeLine, m + cw0 + cw1 + cw2 + cw3 + cw4 + cw5 + 0.5, y + 6.2, {
    maxWidth: cw6 - 1,
  });
  y += 14;

  y = ensureSpace(doc, y, 28, m);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text("Compatibility Summary", m, y);
  y += 3;
  doc.line(m, y, pageW - m, y);
  y += 5;
  const sumRowH = 8;
  doc.setDrawColor(TAN_BORDER[0], TAN_BORDER[1], TAN_BORDER[2]);
  doc.rect(m, y, tableW, sumRowH, "S");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text("Compatibility Score", m + 2, y + 5.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  const scoreLine = `${score} / ${maxScore}${pct2 != null ? ` (${pct2}%)` : ""}`;
  doc.text(scoreLine, m + 58, y + 5.5);
  y += sumRowH;
  doc.rect(m, y, tableW, sumRowH, "S");
  doc.setFont("helvetica", "bold");
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text("Compatibility Grade", m + 2, y + 5.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  doc.text(
    `${grade}${pct2 != null ? ` (${pct2}% and above = Good)` : ""}`,
    m + 58,
    y + 5.5,
    { maxWidth: tableW - 62 },
  );
  y += sumRowH + 6;

  drawFooter(doc, 2, 3);

  doc.addPage();
  y = m;
  y = drawMaroonBanner(doc, y, title, subtitle);
  y += 2;

  const issueLines: string[] = [];
  const crit = match.analysis?.critical_issues ?? [];
  const mod = match.analysis?.moderate_issues ?? [];
  for (const it of [...crit, ...mod]) {
    const lab = it.label ?? it.key ?? "";
    const reason = it.reason ?? "";
    if (lab || reason) issueLines.push(`${lab}: ${reason}`.trim());
  }
  if (issueLines.length === 0 && poruthamRows.length) {
    issueLines.push(
      `Overall: ${match.summary?.result ?? match.result ?? "See Porutham table"}`,
    );
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(MAROON[0], MAROON[1], MAROON[2]);
  doc.text("Marriage compatibility (summary)", m, y);
  y += 4;
  doc.setDrawColor(TAN_BORDER[0], TAN_BORDER[1], TAN_BORDER[2]);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(GREEN[0], GREEN[1], GREEN[2]);
  issueLines.slice(0, 12).forEach((line) => {
    y = ensureSpace(doc, y, 6, m);
    const split = doc.splitTextToSize(line, pageW - 2 * m - 4);
    doc.text(split, m + 2, y);
    y += split.length * 3.8 + 1;
  });

  y += 4;
  const note = match.explanation?.overall?.trim();
  if (note) {
    y = ensureSpace(doc, y, 36, m);
    doc.setDrawColor(GOLD[0], GOLD[1], GOLD[2]);
    doc.setFillColor(255, 252, 240);
    doc.roundedRect(m, y, pageW - 2 * m, 28, 1, 1, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(60, 40, 20);
    doc.text("Astrologer's Note:", m + 2, y + 5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    const wrapped = doc.splitTextToSize(note, pageW - 2 * m - 6);
    doc.text(wrapped, m + 2, y + 9);
    y += 30;
  }

  drawFooter(doc, 3, 3);

  const safeName = `${(bride.name ?? "bride").replace(/\s+/g, "-")}-${(groom.name ?? "groom").replace(/\s+/g, "-")}`;
  doc.save(`match-compatibility-${safeName.slice(0, 40)}.pdf`);
}
